import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#4939D2",
        brand: {
          DEFAULT: "#4939D2",
          dark: "#531fae",
          light: "#4539D2",
        },
        cream: "#FAF7F6",
        "desert-storm": "#FAF7F6",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "system-ui", "sans-serif"],
        manrope: ["var(--font-manrope)", "system-ui", "sans-serif"],
        playfair: ["var(--font-playfair)", "Georgia", "serif"],
        rubik: ["var(--font-rubik)", "system-ui", "sans-serif"],
        inter: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      maxWidth: {
        "8xl": "88rem",
        "125": "31.25rem",
        "145": "36.25rem",
        "146": "36.5rem",
        "173.25": "43.3125rem",
        "206": "51.5rem",
        "208": "52rem",
        "216": "54rem",
        "234": "58.5rem",
        "250": "62.5rem",
        "330": "82.5rem",
      },
      minWidth: {
        "31": "7.75rem",
        "96.25": "24.0625rem",
        "145": "36.25rem",
      },
      spacing: {
        "2.75": "0.6875rem",
        "4.25": "1.0625rem",
        "4.5": "1.125rem",
        "6.5": "1.625rem",
        "7.5": "1.875rem",
        "8.75": "2.1875rem",
        "13": "3.25rem",
        "13.5": "3.375rem",
        "15": "3.75rem",
        "16.25": "4.0625rem",
        "17": "4.25rem",
        "18": "4.5rem",
        "21.5": "5.375rem",
        "22": "5.5rem",
        "23": "5.75rem",
        "25": "6.25rem",
        "26": "6.5rem",
        "27": "6.75rem",
        "30": "7.5rem",
        "31": "7.75rem",
        "32": "8rem",
        "33": "8.25rem",
        "34": "8.5rem",
        "40": "10rem",
        "43": "10.75rem",
        "50": "12.5rem",
        "52": "13rem",
        "65": "16.25rem",
        "70": "17.5rem",
        "75": "18.75rem",
        "78": "19.5rem",
        "80.25": "20.0625rem",
        "85": "21.25rem",
        "90": "22.5rem",
        "100": "25rem",
        "112.5": "28.125rem",
        "120": "30rem",
        "120.5": "30.125rem",
        "140": "35rem",
        "151": "37.75rem",
        "180": "45rem",
        "200": "50rem",
      },
      width: {
        "16.25": "4.0625rem",
        "112.5": "28.125rem",
      },
      height: {
        "7.5": "1.875rem",
        "15": "3.75rem",
        "17": "4.25rem",
        "22": "5.5rem",
        "30": "7.5rem",
        "45": "11.25rem",
        "85": "21.25rem",
      },
      minHeight: {
        "120": "30rem",
        "140": "35rem",
        "151": "37.75rem",
      },
      lineHeight: {
        "7.5": "1.875rem",
        "12": "3rem",
        "15": "3.75rem",
        "16": "4rem",
        "16.25": "4.0625rem",
        "21.5": "5.375rem",
      },
      borderRadius: {
        "4xl": "2rem",
      },
      zIndex: {
        "5": "5",
        "40": "40",
        "1000": "1000",
      },
      transitionDuration: {
        "400": "400ms",
        "800": "800ms",
      },
      keyframes: {
        /* --- values transcribed verbatim from the reference stylesheet --- */
        heroFloatUp: {
          "0%": { transform: "translate(0)" },
          "50%": { transform: "translateY(-18px)" },
          "100%": { transform: "translate(0)" },
        },
        heroFloatDown: {
          "0%": { transform: "translate(0)" },
          "50%": { transform: "translateY(16px)" },
          "100%": { transform: "translate(0)" },
        },
        floatSoft: {
          "0%": { transform: "translate(0) rotate(0)" },
          "50%": { transform: "translateY(-24px) rotate(8deg)" },
          "100%": { transform: "translate(0) rotate(0)" },
        },
        floatSoftReverse: {
          "0%": { transform: "translate(0) rotate(0)" },
          "50%": { transform: "translateY(22px) rotate(-8deg)" },
          "100%": { transform: "translate(0) rotate(0)" },
        },
        floatSoftElement: {
          "0%": { transform: "translate(0) rotate(0)" },
          "50%": { transform: "translateY(-16px) rotate(4deg)" },
          "100%": { transform: "translate(0) rotate(0)" },
        },
        floatSoftElementReverse: {
          "0%": { transform: "translate(0) rotate(0)" },
          "50%": { transform: "translateY(14px) rotate(-4deg)" },
          "100%": { transform: "translate(0) rotate(0)" },
        },
        slowRotate: {
          "0%": { transform: "rotate(0)" },
          "100%": { transform: "rotate(360deg)" },
        },
        buttonShine: {
          "0%": { transform: "translate(0) rotate(30deg)" },
          "100%": { transform: "translate(500px) rotate(30deg)" },
        },
        bounceIn: {
          "0%": { opacity: "0", transform: "scale(.3)" },
          "50%": { transform: "scale(1.1)" },
          "70%": { transform: "scale(.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        ry: {
          to: { transform: "rotateY(1turn)" },
        },
        factRise: {
          "0%": { opacity: "0", visibility: "visible", transform: "translateY(44px)" },
          "100%": { opacity: "1", visibility: "visible", transform: "translateY(0)" },
        },
      },
      animation: {
        heroFloatUp: "heroFloatUp 3s ease-in-out infinite",
        heroFloatDown: "heroFloatDown 2.6s ease-in-out infinite",
        floatSoft: "floatSoft 2.4s ease-in-out infinite",
        floatSoftReverse: "floatSoftReverse 2.4s ease-in-out infinite",
        floatSoftElement: "floatSoftElement 4s ease-in-out infinite",
        floatSoftElementReverse: "floatSoftElementReverse 4.8s ease-in-out infinite",
        slowRotate: "slowRotate 35s linear infinite",
        buttonShine: "buttonShine 1.2s linear infinite",
        bounceIn: "bounceIn 0.8s cubic-bezier(.68,-.55,.27,1.55) forwards",
        "accordion-down": "accordion-down 0.3s ease-out",
        "accordion-up": "accordion-up 0.3s ease-out",
        ry: "ry 32s linear infinite",
      },
      blur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
};

export default config;
